Repository RafaelSantos1234/-batatinha-s-hardware-project, pull requests merged in 2020-08, with the labels that each got.

#6 Adiconei as informações dos coolers.
  src/html/HardWare/Coolers.html
Labels: enhancement

#8 Adicionei as informações das Placas Mães.
  src/html/HardWare/MotherBoards.html
Labels: enhancement

#7 Adicionei as informações das Memórias RAM.
  src/html/HardWare/MemoryRAM.html
Labels: enhancement

#11 Organiza home
  index.html
Labels: documentation, enhancement, help wanted

#4 Página index
  README.md
  assets/GitHub-Mark-64px.png
  global.css
  index.html
  src/css/products.css
  src/css/register.css
  src/html/Computers/Notbooks.html
  src/html/HardWare/Coolers.html
  src/html/HardWare/MemoryRAM.html
  src/html/HardWare/MotherBoards.html
  src/html/cadastro.html
  src/html/index_batatinha.html
  src/js/fileds.js
  src/js/footer.js
Labels: documentation, enhancement, help wanted

#10 Organização da home.
  index.html
Labels: duplicate, invalid

#19 Adicionei o código do rodapé.
  index.html
Labels: enhancement

#22 Processadores info
  src/css/products.css
  src/html/HardWare/Processor.html
Labels: enhancement

#23 Adicionei as informações das placas de video.
  src/html/HardWare/VideoCards.html
Labels: enhancement

#24 css para impedir que a descrição saia do container.
  src/css/products.css
Labels: enhancement

#25 Sobre
  global.css
  index.html
Labels: documentation, enhancement

#27 arrumei a scroll bar do modal para o chrome
  src/css/products.css
Labels: bug

#28 exclui o ms e -o-
  src/css/products.css
Labels: bug

#29 consertei os links quebrados no slide
  index.html
Labels: bug

#30 teste Menu jquery
  src/html/Computers/Netbooks.html
  src/html/Computers/Notbooks.html
  src/html/Computers/Printers.html
  src/html/HardWare/Coolers.html
  src/html/HardWare/HD.html
  src/html/HardWare/MemoryRAM.html
  src/html/HardWare/MotherBoards.html
  src/html/HardWare/Processor.html
  src/html/HardWare/VideoCards.html
  src/html/Peripherals/Mouse&Keybord.html
  src/html/Peripherals/PowerSouce.html
  src/html/Peripherals/Sound.html
  src/html/Portables/CellPhones.html
  src/html/Portables/Tablets.html
  src/html/menu.html
  src/js/products.js
Labels: documentation, enhancement
